# Generated by Django 5.1.15 on 2026-05-23 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text='Unique setting key, e.g. company_name', max_length=100, unique=True)),
                ('value', models.TextField(help_text='Setting value')),
                ('description', models.CharField(blank=True, help_text='Human-readable description of what this setting does', max_length=255)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Unique component code, e.g. BASIC, HRA, PF', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Display name for the component', max_length=100)),
                ('component_type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction')], help_text='Whether this is an earning or deduction', max_length=10)),
                ('calculation_type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage'), ('MANUAL', 'Manual Entry')], help_text="How this component's amount is calculated", max_length=10)),
                ('percentage_value', models.DecimalField(blank=True, decimal_places=4, help_text='Percentage value (e.g. 40.0000 for 40%)', max_digits=8, null=True)),
                ('fixed_value', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed amount in INR', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which this component appears on payslips')),
                ('based_on_component', models.ForeignKey(blank=True, help_text='Component this percentage is calculated on (e.g. HRA based on BASIC)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_components', to='configs.salarycomponent')),
            ],
            options={
                'verbose_name': 'Salary Component',
                'verbose_name_plural': 'Salary Components',
                'ordering': ['display_order', 'code'],
            },
        ),
    ]
