# Generated by Django 5.1.15 on 2026-05-23 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('total_rows', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_report', models.FileField(blank=True, null=True, upload_to='uploads/errors/')),
                ('uploaded_by', models.CharField(default='admin', max_length=100)),
            ],
            options={
                'verbose_name': 'Bulk Upload',
                'verbose_name_plural': 'Bulk Uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkUploadRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.IntegerField()),
                ('employee_code', models.CharField(max_length=20)),
                ('raw_data', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('bulk_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='bulk_upload.bulkupload')),
            ],
            options={
                'verbose_name': 'Upload Row',
                'verbose_name_plural': 'Upload Rows',
                'ordering': ['row_number'],
            },
        ),
    ]
