# Generated by Django 5.1.15 on 2026-05-23 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configs', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('paid_days', models.IntegerField(default=30)),
                ('total_days', models.IntegerField(default=30)),
                ('cl_taken', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='CL Taken')),
                ('sl_taken', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='SL Taken')),
                ('lwp_taken', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='LWP Taken')),
                ('ml_taken', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='ML Taken')),
                ('pl_taken', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='PL Taken')),
                ('gross_salary', models.DecimalField(decimal_places=2, help_text='Sum of all entitled earnings', max_digits=12)),
                ('gross_earned', models.DecimalField(decimal_places=2, help_text='Gross prorated by paid days', max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pdf_file', models.FileField(blank=True, upload_to='payslips/')),
                ('generation_status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('whatsapp_status', models.CharField(choices=[('not_sent', 'Not Sent'), ('sent', 'Sent'), ('failed', 'Failed')], default='not_sent', max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Payslip',
                'verbose_name_plural': 'Payslips',
                'ordering': ['-year', '-created_at'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PayslipItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_name', models.CharField(max_length=100)),
                ('component_code', models.CharField(max_length=20)),
                ('component_type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction')], max_length=10)),
                ('entitled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('earned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('display_order', models.IntegerField(default=0)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payroll.payslip')),
            ],
            options={
                'verbose_name': 'Payslip Item',
                'verbose_name_plural': 'Payslip Items',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount for this component (base amount before proration)', max_digits=12)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_structures', to='configs.salarycomponent')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Employee Salary Structure',
                'verbose_name_plural': 'Employee Salary Structures',
                'ordering': ['component__display_order'],
                'unique_together': {('employee', 'component')},
            },
        ),
    ]
