# Generated by Django 5.1.15 on 2026-05-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_code', models.CharField(help_text='e.g. MMPL-001', max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('grade', models.CharField(blank=True, help_text='e.g. F1, M1', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=30)),
                ('epf_ac_number', models.CharField(blank=True, max_length=50, verbose_name='EPF A/C Number')),
                ('pan_number', models.CharField(blank=True, max_length=10, verbose_name='PAN Number')),
                ('uan_number', models.CharField(blank=True, max_length=20, verbose_name='UAN Number')),
                ('esi_number', models.CharField(blank=True, max_length=20, verbose_name='ESIC Number')),
                ('joining_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['full_name'],
            },
        ),
    ]
